# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/friendlly',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/friendlly',
                'lib_path': 'friendlly'},
  'syms': { 'friendlly.core': { 'friendlly.core.add_cell': ('core.html#add_cell', 'friendlly/core.py'),
                                'friendlly.core.execute_cell': ('core.html#execute_cell', 'friendlly/core.py'),
                                'friendlly.core.fr_line': ('core.html#fr_line', 'friendlly/core.py'),
                                'friendlly.core.inject_js': ('core.html#inject_js', 'friendlly/core.py'),
                                'friendlly.core.load_ipython_extension': ('core.html#load_ipython_extension', 'friendlly/core.py'),
                                'friendlly.core.parse_cell': ('core.html#parse_cell', 'friendlly/core.py'),
                                'friendlly.core.unload_ipython_extension': ('core.html#unload_ipython_extension', 'friendlly/core.py'),
                                'friendlly.core.update_cell': ('core.html#update_cell', 'friendlly/core.py')}}}
